export default {
  CREATE_TODO: "CREATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO_TEXT: "EDIT_TODO",
  EDIT_TODO_COMPLETED: "EDIT_TODO_COMPLETED",
  EDIT_TODO_TITLE: "EDIT_TODO_TITLE",
  CLEAR_TODOS: "CLEAR_TODOS",

  CHANGE_FILTER_TYPE: "CHANGE_FILTER_TYPE",
};
